### ISSUE TITLE
Labels size adjusted by row and column total number

### ISSUE THREAD

**Issue by marcora** [jbengler/tidyheatmap#1]
It would be nice to add this feature to tidyheatmap, see https://github.com/stemangiola/tidyHeatmap

**Comment by jbengler** [comment]
As the final heatmap area depends on the amount of additional row and column annotation, I imagine the computational solution to this request to be quite complex.

I would recommend to either adjust the `cellwidth` and `cellheight` parameters or `fontsize_row` and `fontsize_col` to your liking.

**Comment by marcora** [comment]
tidyheatmap does it, perhaps inspecting its code could reveal a not so complex implementation
